const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const healthFill = document.getElementById('healthFill');
const levelEl = document.getElementById('level');
const expEl = document.getElementById('exp');
const expNextEl = document.getElementById('expNext');
const enemyCountEl = document.getElementById('enemyCount');
const currentSkillEl = document.getElementById('currentSkill');
const cooldownBar = document.getElementById('cooldownBar');
const cooldownFill = document.getElementById('cooldownFill');

// Sprite'lar (aynı)
const playerBase64 = 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABQklEQVRYhWNgGAUjHTCSq/HWUoX/yHy16AdkmUWWJnTLKXEEyRpwWU6uI0hSTMhychxBtEKY5apR9xkYGBgYbi9TRJFHFyfWEUzEOoBWgIVUDeg+JyROCAx4CBDtAFicblzwGa+6jQs+0yYRdrsKw3OAfwIvXgfAQOnutwTNJ6gA2WJCDlCLfsCITT0+h+BMhNgMQraIlKIYZhY2h2A4AJ/FMPD/OsN/BoYHGGKMmvhDFJtDqJoLIA4jDQydbDhsHUBSUVwy6S3RanryhKnnAGIsJtcheB1QuvstIzkpG92MAwcO/D/dGoxVHmsaKN39lhGWVwnlbXwAptfBwYHxq3Uug2n1WsIOwFZakeMIXHrQzSfJYGKjA5flDQ0N/x0cHBgcHBzg8iTlApjBuBxCSXTRDRw4cOD/gQMHKErYo4CqAABSyIHYXpwtTgAAAABJRU5ErkJggg==';
const enemyBase64 = 'iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAYAAAByDd+UAAAA9klEQVRIie2UQRKCMAxFU8YT0QVeSQ+kV5JFudJ3oZ0JIW1SpjiO419Rkv5HQlOiX1do3fAYR/D1eVmaPJqSJWwP1J1YgrVCXUkAQEQ0x6jGp5ReZiGYfmYCAFD2ATbQKSXicQs6WMDeMoFzjESAWp0nLmW21DosUtbhcR0aL9RzUr9zLDg0jwD/X10HH0TryiAKFVMQDM+TG+RU3lcCqy9dsFxpZc41aLFCU/YtVvqItfa2sgIIYk10Y5BLR9idPV/frIEvZNIROvTy5oXkLg5asEeVpbFYVSih1hCXQLV9ZkuzQc2kliPbugFqfdeMPR/y10f0BG1uWAACK0I/AAAAAElFTkSuQmCC';
const bossBase64 = 'iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAACQklEQVRoge2Yv27CMBDGzxFTkSqmjpU781KoT8DUNWZl6hNU8FDsiJEpQqKrO6QOjuM/d7aTQJvfhIji3Ofv7nwJwB0hpZSx97KcgaSgi2CMkeMq8oaDRw/cdCLGmVGE+ESE/ncxeGqRA0SmWZIjO16RgopJGSmlFCCC90U5ogtYHReoNUIiNmwTXEOAcD6L7AjVBQCcE6Usg+v4nEEL2fFKxoigkCJmhnlAqgBX2pRS/F4XKcsDQMCRHC64drCUoq5QdhPE+Tp6TaeQPtOoEaFwiCmlaP4P0RGSsxYwbdMG5+takOGYb+2WkL6LWbFhAkB/krTXyZ5X9Q+HGJ0CYJiOZNKIcYhQ7Hl1E+RhNrQAHUq32r9VAPDpvF5gT+Z7oKkdCwVAPWY8miCTVrHnFuObjVLhfN1qTp32+2juKDHOEWV1XLCYRrBdnjr3fB++qMuQ2PFKemct5UxIkC34IVkdFww1/fpSDSPiaflOiYuEio1cC6Y75/kFfW8oxbBDI0B3c0kvVtvlSVICN8nljC1DUO8jAO0UUmJers/kIJSYmAbgS3FUavVZzLogX2qFjgS0I33RSrdr9/p5foGPw2tww4M1MmZrVSmMiWF0R2zENJSWkNg3upzEdsXRPmLbSGntTRHZ3FDT69gjSJZifxQYgN8NxViuYNwAIDiCXTAnlGcyjBsmfbsTs2lRNdKnO7Frdw5E7Hu2/sBUh3JsTJaTPUZUblezjyhjNAUAo0b6/HzTN3/mQLyLQXFiYmLi//EDW8oiJCb19XYAAAAASUVORK5CYII=';
const bgTileBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAACS0lEQVRoge2a0W6DIBRAr4WS0CbG1GUP/dp90z5hH+PDsi7GtDUxGPeAMxYBBbRI43lZgmzew+XOS2309fkBMvbSUYA97FY1Xz47IDYB32wCvtkEfIMB+Q7BjeAzsAn4JngB7DuAB0p6Kh9H4jLX/8paBEp6ko4XNAGthn8BVeh9uEYq08CATMtgzvklSab/oQtN0qpwjGZOjKLnXEgsjHgTsIieIzgE/2/UjwCzXX5OPwlbBsxxXH5Ol4TgMxDyeQAB2D2JCRKfnVX96x6PHQYCR/SmutQpNU83m
